version: "3.9"

services:
  backend:
    build: .
    container_name: handwritten_api
    restart: always
    volumes:
      - results_data:/app/api_results
      - temp_data:/app/temp_uploads
    environment:
      - PYTHONUNBUFFERED=1
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: handwritten_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  results_data:
  temp_data:
